account_id = "e64f119e1bec3ee9fd568daf2a8d5ee6"
compatibility_date = "2023-05-30"
main = "src/index.js"
name = "suisei-worker"
node_compat = true
workers_dev = true
route = { pattern = "suisei.cc/podcast.xml", zone_name = "suisei.cc" }
